// <auto-generated />
namespace Serwis_UsprawniającyModelProdukcyjny.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pierwszamigracja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pierwszamigracja));
        
        string IMigrationMetadata.Id
        {
            get { return "202205071402187_pierwsza migracja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
